"""Reusable UI component functions for the Streamlit frontend.
"""

from __future__ import annotations

import json
import io
from typing import Any

import plotly.io as pio
import streamlit as st


# ── Message bubble ────────────────────────────────────────────────────────────

def render_user_message(content: str) -> None:
    """Render a user chat bubble."""
    with st.chat_message("user", avatar="👤"):
        st.markdown(content)


def render_assistant_message(response: dict, client=None) -> None:
    """Render a full assistant response: explanation, SQL, chart, table, exports."""
    with st.chat_message("assistant", avatar="🤖"):
        status = response.get("status", "success")

        # ── Error state ───────────────────────────────────────────────────
        if status in ("failed", "blocked"):
            st.error(f"⚠️ {response.get('error_message', 'Something went wrong.')}")
            return

        # ── Description (one-liner from LLM) ─────────────────────────────
        if description := response.get("description"):
            st.caption(f"_{description}_")

        # ── Explanation / insights ────────────────────────────────────────
        if explanation := response.get("explanation"):
            st.markdown(explanation)

        # ── Chart ─────────────────────────────────────────────────────────
        chart_json = response.get("chart_json", "")
        if chart_json:
            render_chart(chart_json, response.get("chart_type", ""))

        # ── Results table ─────────────────────────────────────────────────
        rows = response.get("rows", [])
        columns = response.get("columns", [])
        row_count = response.get("row_count", 0)
        if rows:
            render_results_table(rows, columns, row_count,
                                 was_truncated=response.get("was_truncated", False))

        # ── SQL viewer (collapsible) ──────────────────────────────────────
        if sql := response.get("sql"):
            render_sql_viewer(sql)

        # ── Metadata bar ──────────────────────────────────────────────────
        render_metadata_bar(response)

        # ── Feedback buttons ─────────────────────────────────────────────
        message_id = response.get("message_id")
        if message_id and client:
            render_feedback_buttons(message_id, client)


# ── Chart ─────────────────────────────────────────────────────────────────────

def render_chart(chart_json: str, chart_type: str) -> None:
    """Deserialise and render a Plotly figure from JSON."""
    try:
        fig = pio.from_json(chart_json)
        st.plotly_chart(fig, use_container_width=True, key=f"chart_{id(chart_json)}")
    except Exception as exc:
        st.warning(f"Chart rendering failed: {exc}")


# ── Results table ─────────────────────────────────────────────────────────────

def render_results_table(
    rows: list[dict],
    columns: list[str],
    row_count: int,
    *,
    was_truncated: bool = False,
) -> None:
    """Render the query result as a Streamlit dataframe with export buttons."""
    import pandas as pd

    df = pd.DataFrame(rows, columns=columns) if rows else pd.DataFrame()

    if was_truncated:
        st.caption(
            f"⚠️ Showing first {row_count:,} rows. "
            "Add a narrower filter to see all results."
        )

    st.dataframe(df, use_container_width=True, hide_index=True)

    if not df.empty:
        col1, col2, _ = st.columns([1, 1, 4])
        with col1:
            st.download_button(
                "⬇ CSV",
                data=df.to_csv(index=False).encode("utf-8"),
                file_name="query_results.csv",
                mime="text/csv",
                use_container_width=True,
            )
        with col2:
            st.download_button(
                "⬇ Excel",
                data=_df_to_excel_bytes(df),
                file_name="query_results.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                use_container_width=True,
            )


def _df_to_excel_bytes(df) -> bytes:
    """Convert a DataFrame to Excel bytes for the download button."""
    import pandas as pd
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Results")
    return buf.getvalue()


# ── SQL viewer ────────────────────────────────────────────────────────────────

def render_sql_viewer(sql: str) -> None:
    """Render the generated SQL in a collapsible code block."""
    with st.expander("🔍 View generated SQL", expanded=False):
        st.code(sql, language="sql")
        st.caption("This SQL was generated by AI, validated, and executed read-only.")


# ── Metadata bar ──────────────────────────────────────────────────────────────

def render_metadata_bar(response: dict) -> None:
    """Render execution time and row count as a compact metric row."""
    exec_ms = response.get("execution_time_ms", 0)
    total_ms = response.get("total_latency_ms", 0)
    row_count = response.get("row_count", 0)
    chart_type = response.get("chart_type", "")

    cols = st.columns(4)
    with cols[0]:
        st.metric("Rows", f"{row_count:,}")
    with cols[1]:
        st.metric("SQL time", f"{exec_ms:.0f} ms")
    with cols[2]:
        st.metric("Total latency", f"{total_ms:.0f} ms")
    with cols[3]:
        st.metric("Chart", chart_type or "—")


# ── Feedback buttons ──────────────────────────────────────────────────────────

def render_feedback_buttons(message_id: int, client) -> None:
    """Render thumbs-up / thumbs-down feedback buttons."""
    from state import State

    if State.feedback_already_sent(message_id):
        st.caption("✅ Feedback submitted — thank you!")
        return

    col1, col2, _ = st.columns([1, 1, 6])
    with col1:
        if st.button("👍", key=f"up_{message_id}", help="This was helpful"):
            result = client.submit_feedback(message_id, is_positive=True)
            if result.ok:
                State.mark_feedback_sent(message_id)
                st.rerun()
    with col2:
        if st.button("👎", key=f"down_{message_id}", help="This was not helpful"):
            result = client.submit_feedback(message_id, is_positive=False)
            if result.ok:
                State.mark_feedback_sent(message_id)
                st.rerun()


# ── Schema browser ────────────────────────────────────────────────────────────

def render_schema_browser(schema_data: dict) -> None:
    """Render the schema browser as an expandable tree in the sidebar."""
    tables = schema_data.get("tables", [])
    role = schema_data.get("role", "")
    st.sidebar.markdown(f"**Schema** · `{role}` role · {len(tables)} tables")

    for table in sorted(tables, key=lambda t: t["name"]):
        with st.sidebar.expander(f"📋 {table['name']}", expanded=False):
            for col in table.get("columns", []):
                st.sidebar.caption(f"  `{col}`")


# ── Conversation list (sidebar) ───────────────────────────────────────────────

def render_conversation_list(conversations: list[dict], on_select, on_delete) -> None:
    """Render the conversation history list in the sidebar."""
    if not conversations:
        st.sidebar.caption("No conversations yet.")
        return

    for conv in conversations:
        col1, col2 = st.sidebar.columns([5, 1])
        with col1:
            if st.button(
                conv.get("title", "Untitled")[:40],
                key=f"conv_{conv['id']}",
                use_container_width=True,
            ):
                on_select(conv["id"])
        with col2:
            if st.button("🗑", key=f"del_{conv['id']}", help="Delete"):
                on_delete(conv["id"])


# ── Thinking spinner ──────────────────────────────────────────────────────────

def thinking_placeholder() -> Any:
    """Return a Streamlit empty slot to fill with the thinking indicator."""
    return st.empty()
